// Tests for module packs: `faraday pack list` + `faraday pack add`. Uses a real
// tmpdir lesson generated by the scaffold pipeline, no install.
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { generateLesson } from "./generate.mjs";
import { listPacks, installPack, removePack, resolvePack, validateManifest, readManifestAt, readPackSkill, defaultPackNames } from "./pack.mjs";

async function tmp() {
  return fs.mkdtemp(path.join(os.tmpdir(), "faraday-pack-test-"));
}
const read = (dir, rel) => fs.readFile(path.join(dir, rel), "utf8");
const exists = async (p) => !!(await fs.stat(p).catch(() => null));

test("listPacks includes all shipped packs", async () => {
  const packs = await listPacks();
  const names = packs.map((p) => p.name);
  for (const n of ["three", "tutor", "srs", "lecture-design"]) {
    assert.ok(names.includes(n), `expected a \`${n}\` pack`);
  }
  const three = packs.find((p) => p.name === "three");
  assert.ok(three.runtime?.dependencies?.["@faraday-academy/three"], "three pins its runtime pkg");
  assert.ok(three.runtime?.variants?.physics, "three exposes a physics variant");
  assert.ok(three.skill?.reference, "three ships a skill reference");
});

async function scaffold(name) {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name, uuid: () => "fixed-id" });
  return target;
}

test("installPack(tutor) drops the durable server + wiring", async () => {
  const target = await scaffold("Tutor Host");
  await installPack("tutor", { fromDir: target });

  const pkg = JSON.parse(await read(target, "package.json"));
  assert.equal(pkg.dependencies["@faraday-academy/tutor"], "0.1.0");
  for (const dep of ["ai", "@ai-sdk/workflow", "workflow", "nitro", "zod"]) {
    assert.ok(pkg.dependencies[dep], `server dep ${dep} missing`);
  }
  assert.ok(await exists(path.join(target, "api/chat.post.ts")), "nitro route copied");
  assert.ok(await exists(path.join(target, "workflows/tutor-agent.ts")), "workflow agent copied");
  assert.ok(await exists(path.join(target, "docs/tutor.md")), "tutor guide copied");
  assert.match(await read(target, "vite.config.ts"), /nitro|workflow/);
  assert.match(await read(target, "pnpm-workspace.yaml"), /nodeLinker:\s*hoisted/);
  assert.match(await read(target, "src/app.css"), /@faraday-academy\/tutor\/styles\.css/);
  assert.ok(await exists(path.join(target, ".faraday/packs/tutor/pack.md")), "skill installed");
});

test("installPack(srs) copies the author-editable component, no new npm deps", async () => {
  const target = await scaffold("SRS Host");
  const before = JSON.parse(await read(target, "package.json"));
  await installPack("srs", { fromDir: target });

  assert.ok(await exists(path.join(target, "src/lesson/srs/Flashcards.tsx")), "component copied");
  assert.ok(await exists(path.join(target, "src/lesson/srs/scheduler.ts")), "scheduler copied");
  assert.ok(await exists(path.join(target, ".faraday/packs/srs/pack.md")), "skill installed");

  const after = JSON.parse(await read(target, "package.json"));
  assert.deepEqual(after.dependencies, before.dependencies, "srs adds no runtime deps");
});

test("installPack(lecture-design) installs a skill FOLDER, no runtime", async () => {
  const target = await scaffold("Pedagogy Host");
  const result = await installPack("lecture-design", { fromDir: target });

  // skill reference is a directory -> the whole folder is installed
  for (const f of ["overview.md", "spaced-retrieval.md", "methods.md"]) {
    assert.ok(await exists(path.join(target, ".faraday/packs/lecture-design", f)), `${f} installed`);
  }
  assert.equal(result.addedDeps.length, 0, "skill-only pack adds no deps");
  const agents = await read(target, "AGENTS.md");
  assert.ok(agents.includes("Pack `lecture-design`:"), "AGENTS.md pointer added");
});

test("installPack(three) wires the runtime half AND the skill half", async () => {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "Pack Host", uuid: () => "fixed-id" });

  const result = await installPack("three", { fromDir: target });
  assert.equal(result.lessonRoot, target);

  // runtime half: deps pinned + sorted
  const pkg = JSON.parse(await read(target, "package.json"));
  assert.equal(pkg.dependencies["@faraday-academy/three"], "0.1.0");
  assert.ok(pkg.dependencies["@react-three/fiber"]);
  assert.ok(pkg.devDependencies["@types/three"]);
  const keys = Object.keys(pkg.dependencies);
  assert.deepEqual(keys, [...keys].sort((a, b) => a.localeCompare(b)), "deps stay sorted");

  // runtime half: css import injected
  const css = await read(target, "src/app.css");
  assert.ok(css.includes('@import "@faraday-academy/three/styles.css";'), "three css wired");

  // runtime half: examples copied
  assert.ok(await exists(path.join(target, "docs/examples/curriculum3d.tsx")), "example copied");

  // skill half: reference installed + pointer in AGENTS.md
  assert.ok(await exists(path.join(target, ".faraday/packs/three/pack.md")), "skill ref installed");
  const agents = await read(target, "AGENTS.md");
  assert.ok(agents.includes("Pack `three`:"), "AGENTS.md pointer added");

  // provenance records the pack
  const prov = JSON.parse(await read(target, ".faraday/provenance.json"));
  assert.ok(prov.packs.includes("three"), "provenance records the pack");
});

test("installPack is idempotent + supports the physics variant", async () => {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "Pack Host 2", uuid: () => "fixed-id" });

  await installPack("three", { fromDir: target, variant: "physics" });
  await installPack("three", { fromDir: target, variant: "physics" }); // twice = no dupes

  const pkg = JSON.parse(await read(target, "package.json"));
  assert.ok(pkg.dependencies["@react-three/rapier"], "physics variant dep pinned");

  const css = await read(target, "src/app.css");
  const occurrences = css.split('@import "@faraday-academy/three/styles.css";').length - 1;
  assert.equal(occurrences, 1, "css import not duplicated on re-run");

  const agents = await read(target, "AGENTS.md");
  const pointers = agents.split("Pack `three`:").length - 1;
  assert.equal(pointers, 1, "AGENTS.md pointer not duplicated on re-run");

  const prov = JSON.parse(await read(target, ".faraday/provenance.json"));
  assert.equal(prov.packs.filter((p) => p === "three:physics").length, 1, "provenance not duplicated");
});

test("installPack rejects an unknown pack, a lesson-less dir, and a bad variant", async () => {
  const base = await tmp();
  // unknown pack fails at manifest read, before the lesson lookup
  await assert.rejects(() => installPack("nope", { fromDir: base }), /Unknown pack: nope/);
  // a dir with no lesson above it
  await assert.rejects(() => installPack("three", { fromDir: base }), /not inside a Faraday lesson/);

  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "Pack Host 3", uuid: () => "fixed-id" });
  await assert.rejects(() => installPack("three", { fromDir: target, variant: "nonsense" }), /no variant/);
});

test("validateManifest catches shape errors and passes real packs", async () => {
  assert.deepEqual(validateManifest({ displayName: "ok" }), []);
  // a real shipped pack validates clean
  const three = await resolvePack("three");
  assert.deepEqual(validateManifest(await readManifestAt(three.packDir)), []);

  const errs = validateManifest({
    runtime: { copy: [{ from: "x" }], dependencies: { pkg: 1 } },
    skill: { reference: 5 },
  });
  assert.ok(errs.some((e) => /displayName is required/.test(e)));
  assert.ok(errs.some((e) => /runtime\.copy\[0\]/.test(e)));
  assert.ok(errs.some((e) => /runtime\.dependencies/.test(e)));
  assert.ok(errs.some((e) => /skill\.reference/.test(e)));
});

test("resolvePack classifies official names and local paths", async () => {
  const off = await resolvePack("three");
  assert.equal(off.name, "three");
  assert.equal(off.source, "three");
  assert.ok(await exists(path.join(off.packDir, "pack.json")));
  await assert.rejects(() => resolvePack("does-not-exist"), /Unknown pack/);

  // a local pack dir
  const base = await tmp();
  const packDir = path.join(base, "my-pack");
  await fs.mkdir(packDir, { recursive: true });
  await fs.writeFile(
    path.join(packDir, "pack.json"),
    JSON.stringify({ displayName: "Mine", skill: { reference: "g.md" } }),
  );
  await fs.writeFile(path.join(packDir, "g.md"), "# guide");
  const local = await resolvePack(packDir);
  assert.equal(local.packDir, packDir);
  assert.equal(local.source, packDir);
});

test("default packs: audience + lecture-design are flagged, readPackSkill reads file & folder", async () => {
  const defaults = await defaultPackNames();
  assert.ok(defaults.includes("lecture-design"), "lecture-design is default");
  assert.ok(defaults.includes("audience"), "audience is default");

  // folder skill (lecture-design) → multiple files
  const ld = await resolvePack("lecture-design");
  const ldFiles = await readPackSkill(ld.packDir, await readManifestAt(ld.packDir));
  assert.ok(ldFiles.length > 1, "lecture-design skill is a multi-file folder");
  assert.ok(ldFiles.every((f) => f.path.endsWith(".md") && typeof f.content === "string"));

  // file skill (audience) → single file
  const aud = await resolvePack("audience");
  const audFiles = await readPackSkill(aud.packDir, await readManifestAt(aud.packDir));
  assert.equal(audFiles.length, 1, "audience skill is a single file");
  assert.match(audFiles[0].content, /Audience/);
});

test("faraday new auto-installs default packs (skill-only), --no-defaults opts out", async () => {
  const withBase = await tmp();
  await generateLesson({ targetDir: path.join(withBase, "l"), name: "Def On", uuid: () => "id" });
  const prov = JSON.parse(await read(path.join(withBase, "l"), ".faraday/provenance.json"));
  assert.ok(prov.packs.includes("lecture-design") && prov.packs.includes("audience"), "defaults recorded");
  assert.ok(await exists(path.join(withBase, "l", ".faraday/packs/audience/audience.md")), "audience skill installed");
  assert.ok(await exists(path.join(withBase, "l", ".faraday/packs/lecture-design/overview.md")), "lecture-design folder installed");
  // skill-only: no new deps beyond the runtime pin
  const pkg = JSON.parse(await read(path.join(withBase, "l"), "package.json"));
  assert.ok(!Object.keys(pkg.dependencies).some((d) => d.includes("lecture-design") || d === "audience"));

  const noDef = await tmp();
  await generateLesson({ targetDir: path.join(noDef, "l"), name: "Def Off", noDefaults: true, uuid: () => "id" });
  const prov2 = JSON.parse(await read(path.join(noDef, "l"), ".faraday/provenance.json"));
  assert.ok(!(prov2.packs ?? []).length, "no default packs with --no-defaults");
});

test("removePack un-registers a pack and reverses its unshared deps/css", async () => {
  const target = await scaffold("Remove Host");
  await installPack("three", { fromDir: target });
  assert.ok(await exists(path.join(target, ".faraday/packs/three/pack.md")), "installed first");

  const r = await removePack("three", { fromDir: target });
  assert.equal(r.manifestResolved, true);

  // skill half + pointer + provenance gone
  assert.equal(await exists(path.join(target, ".faraday/packs/three")), false, "skill dir removed");
  assert.ok(!(await read(target, "AGENTS.md")).includes("Pack `three`:"), "AGENTS.md pointer stripped");
  const prov = JSON.parse(await read(target, ".faraday/provenance.json"));
  assert.ok(!prov.packs.some((p) => (typeof p === "string" ? p : p.name).startsWith("three")), "provenance entry gone");

  // reversible runtime config reversed
  const pkg = JSON.parse(await read(target, "package.json"));
  assert.ok(!("@faraday-academy/three" in pkg.dependencies), "three dep removed");
  assert.ok(!(await read(target, "src/app.css")).includes("@faraday-academy/three/styles.css"), "three css removed");
  assert.ok(r.removedDeps.includes("@faraday-academy/three"));

  // copied files are reported, not deleted
  assert.ok(r.leftFiles.includes("docs/examples"));

  await assert.rejects(() => removePack("three", { fromDir: target }), /not installed/);
});

test("removePack keeps a dependency still required by another installed pack", async () => {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "Shared Deps", uuid: () => "fixed-id" });

  // a local pack that also depends on @react-three/fiber (shared with `three`)
  const packDir = path.join(base, "viz-pack");
  await fs.mkdir(packDir, { recursive: true });
  await fs.writeFile(
    path.join(packDir, "pack.json"),
    JSON.stringify({ displayName: "Viz", runtime: { dependencies: { "@react-three/fiber": "^9.0.0" } } }),
  );

  await installPack("three", { fromDir: target });
  await installPack("viz-pack", { fromDir: target, packDir, source: packDir });

  const r = await removePack("three", { fromDir: target });
  const pkg = JSON.parse(await read(target, "package.json"));
  assert.ok("@react-three/fiber" in pkg.dependencies, "shared dep kept");
  assert.ok(!("@faraday-academy/three" in pkg.dependencies), "unshared three dep removed");
  assert.ok(!r.removedDeps.includes("@react-three/fiber"), "shared dep not reported as removed");
});

test("installPack from an external (local) source records {name, source} in provenance", async () => {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "External Host", uuid: () => "fixed-id" });

  const packDir = path.join(base, "vocab-pack");
  await fs.mkdir(packDir, { recursive: true });
  await fs.writeFile(
    path.join(packDir, "pack.json"),
    JSON.stringify({ displayName: "Vocab", skill: { reference: "guide.md", loadWhen: "teaching vocab" } }),
  );
  await fs.writeFile(path.join(packDir, "guide.md"), "# vocab guide");

  const result = await installPack("vocab-pack", { fromDir: target, packDir, source: packDir });
  assert.equal(result.source, packDir);
  assert.ok(await exists(path.join(target, ".faraday/packs/vocab-pack/guide.md")), "skill installed");

  const prov = JSON.parse(await read(target, ".faraday/provenance.json"));
  const entry = prov.packs.find((p) => typeof p === "object" && p.name === "vocab-pack");
  assert.ok(entry, "external pack recorded as an object");
  assert.equal(entry.source, packDir);
});
