// Tests for module packs: `faraday pack list` + `faraday pack add`. Uses a real
// tmpdir lesson generated by the scaffold pipeline, no install.
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { generateLesson } from "./generate.mjs";
import { runFaradayCli } from "./cli.mjs";
import { listPacks, installPack, removePack, resolvePack, validateManifest, validatePackDir, readManifestAt, readPackSkill, defaultPackNames, scaffoldPack } from "./pack.mjs";

/** Run the CLI capturing stdout/stderr (throws on non-zero). setExitCode is
 *  captured locally so a rejection test doesn't poison the runner's exit code. */
async function cli(args) {
  let out = "", err = "", code = 0;
  await runFaradayCli(args, {
    cwd: process.cwd(),
    stdout: (s) => (out += s),
    stderr: (s) => (err += s),
    setExitCode: (c) => (code = c),
    throwOnError: true,
  });
  return { out, err, code };
}

async function tmp() {
  return fs.mkdtemp(path.join(os.tmpdir(), "faraday-pack-test-"));
}
const read = (dir, rel) => fs.readFile(path.join(dir, rel), "utf8");
const exists = async (p) => !!(await fs.stat(p).catch(() => null));

test("listPacks includes all shipped packs", async () => {
  const packs = await listPacks();
  const names = packs.map((p) => p.name);
  for (const n of ["three", "tutor", "srs", "lecture-design", "audience", "exam", "slide-view", "textbook-view", "notes", "map2d", "game2d", "storybook-game2d", "sim2d", "stem-methods"]) {
    assert.ok(names.includes(n), `expected a \`${n}\` pack`);
  }
  assert.ok(!names.includes("kids"), "kids was folded into storybook-game2d");
  const sim2d = packs.find((p) => p.name === "sim2d");
  assert.ok(sim2d?.runtime?.dependencies?.gsap, "sim2d pins gsap");
  assert.equal(sim2d?.default, true, "sim2d is a default pack");
  const game2d = packs.find((p) => p.name === "game2d");
  assert.ok(game2d?.runtime?.dependencies?.["pixi.js"], "game2d pins pixi.js");
  assert.ok(game2d?.runtime?.dependencies?.["matter-js"], "game2d pins matter-js");
  assert.equal(game2d?.default, true, "game2d is a default pack");
  const story = packs.find((p) => p.name === "storybook-game2d");
  assert.deepEqual(story?.requires, ["game2d"], "storybook-game2d requires game2d");
  assert.equal(story?.default, true, "storybook-game2d is a default pack");
  // every shipped pack must have a valid manifest
  for (const p of packs) {
    const errs = validateManifest(await readManifestAt((await resolvePack(p.name)).packDir));
    assert.deepEqual(errs, [], `${p.name} manifest invalid: ${errs.join("; ")}`);
  }
  // every official pack declares a known category (drives `pack list` grouping)
  const CATEGORIES = new Set(["course", "lecture", "runtime", "methodology"]);
  for (const p of packs) {
    assert.ok(CATEGORIES.has(p.category), `${p.name} must have a known category, got ${p.category}`);
  }
  const three = packs.find((p) => p.name === "three");
  assert.ok(three.runtime?.dependencies?.["@faraday-academy/three"], "three pins its runtime pkg");
  assert.ok(three.runtime?.variants?.physics, "three exposes a physics variant");
  assert.ok(three.skill?.reference, "three ships a skill reference");
});

async function scaffold(name, { noDefaults = false } = {}) {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name, uuid: () => "fixed-id", noDefaults });
  return target;
}

test("installPack(tutor) drops the durable server + wiring", async () => {
  const target = await scaffold("Tutor Host");
  await installPack("tutor", { fromDir: target });

  const pkg = JSON.parse(await read(target, "package.json"));
  assert.equal(pkg.dependencies["@faraday-academy/tutor"], "0.2.0");
  for (const dep of ["ai", "@ai-sdk/workflow", "workflow", "nitro", "zod"]) {
    assert.ok(pkg.dependencies[dep], `server dep ${dep} missing`);
  }
  assert.ok(await exists(path.join(target, "api/chat.post.ts")), "nitro route copied");
  assert.ok(await exists(path.join(target, "workflows/tutor-agent.ts")), "workflow agent copied");
  assert.ok(await exists(path.join(target, "docs/tutor.md")), "tutor guide copied");
  assert.match(await read(target, "vite.config.ts"), /nitro|workflow/);
  assert.match(await read(target, "pnpm-workspace.yaml"), /nodeLinker:\s*hoisted/);
  assert.match(await read(target, "src/app.css"), /@faraday-academy\/tutor\/styles\.css/);
  assert.ok(await exists(path.join(target, ".faraday/packs/tutor/pack.md")), "skill installed");
});

test("installPack(srs) copies the author-editable component, no new npm deps", async () => {
  const target = await scaffold("SRS Host");
  const before = JSON.parse(await read(target, "package.json"));
  await installPack("srs", { fromDir: target });

  assert.ok(await exists(path.join(target, "src/lesson/srs/Flashcards.tsx")), "component copied");
  assert.ok(await exists(path.join(target, "src/lesson/srs/scheduler.ts")), "scheduler copied");
  assert.ok(await exists(path.join(target, ".faraday/packs/srs/pack.md")), "skill installed");

  const after = JSON.parse(await read(target, "package.json"));
  assert.deepEqual(after.dependencies, before.dependencies, "srs adds no runtime deps");
});

test("installPack(map2d) copies the presentation component, no new npm deps", async () => {
  const target = await scaffold("Map Host");
  const before = JSON.parse(await read(target, "package.json"));
  await installPack("map2d", { fromDir: target });

  assert.ok(await exists(path.join(target, "src/lesson/map2d/map2d.tsx")), "presentation copied");
  assert.ok(await exists(path.join(target, "src/lesson/map2d/index.ts")), "index copied");
  assert.ok(await exists(path.join(target, ".faraday/packs/map2d/pack.md")), "skill installed");

  const after = JSON.parse(await read(target, "package.json"));
  assert.deepEqual(after.dependencies, before.dependencies, "map2d adds no runtime deps");
});

test("installPack(game2d) pins Pixi/Matter/Howler and copies glue", async () => {
  const target = await scaffold("Game2D Host", { noDefaults: true });
  await installPack("game2d", { fromDir: target });

  const pkg = JSON.parse(await read(target, "package.json"));
  assert.ok(pkg.dependencies["pixi.js"], "pixi.js pinned");
  assert.ok(pkg.dependencies["@pixi/react"], "@pixi/react pinned");
  assert.ok(pkg.dependencies["matter-js"], "matter-js pinned");
  assert.ok(pkg.dependencies.howler, "howler pinned");
  assert.ok(pkg.devDependencies["@assetvault/cli"], "@assetvault/cli pinned");
  assert.ok(await exists(path.join(target, "src/lesson/game2d/Game2D.tsx")), "Game2D copied");
  assert.ok(await exists(path.join(target, "src/lesson/game2d/paths.ts")), "game2dAsset helper copied");
  assert.ok(await exists(path.join(target, "src/lesson/game2d/physics.tsx")), "physics copied");
  assert.ok(await exists(path.join(target, "src/lesson/game2d/tilemap.tsx")), "tilemap copied");
  assert.ok(await exists(path.join(target, "src/lesson/game2d/audio.ts")), "audio copied");
  assert.ok(await exists(path.join(target, "scripts/game2d-assets.mjs")), "assetvault wrapper copied");
  assert.ok(await exists(path.join(target, "public/assets/game2d/README.md")), "asset README copied");
  assert.ok(await exists(path.join(target, "public/assets/game2d/recommended.json")), "recommended packs copied");
  assert.ok(await exists(path.join(target, ".faraday/packs/game2d/assetvault.md")), "assetvault skill installed");
  assert.ok(await exists(path.join(target, ".faraday/packs/game2d/SKILL.md")), "folder skill installed");
});

test("installPack(storybook-game2d) requires game2d and copies the story shell", async () => {
  const target = await scaffold("Story Host", { noDefaults: true });
  await installPack("storybook-game2d", { fromDir: target });

  assert.ok(await exists(path.join(target, "src/lesson/game2d/Game2D.tsx")), "game2d installed via requires");
  assert.ok(await exists(path.join(target, "src/lesson/storybook-game2d/StorybookGame.tsx")), "story shell copied");
  assert.ok(await exists(path.join(target, ".faraday/packs/storybook-game2d/SKILL.md")), "skill installed");
  assert.ok(await exists(path.join(target, ".faraday/packs/storybook-game2d/pedagogy.md")), "kids pedagogy folded in");
  const pkg = JSON.parse(await read(target, "package.json"));
  assert.ok(pkg.dependencies["pixi.js"], "pixi arrives through game2d requires");
});

test("installPack(sim2d) pins GSAP and copies simulation glue", async () => {
  const target = await scaffold("Sim2D Host", { noDefaults: true });
  await installPack("sim2d", { fromDir: target });

  const pkg = JSON.parse(await read(target, "package.json"));
  assert.ok(pkg.dependencies.gsap, "gsap pinned");
  assert.ok(await exists(path.join(target, "src/lesson/sim2d/useSimTime.ts")), "useSimTime copied");
  assert.ok(await exists(path.join(target, "src/lesson/sim2d/SvgStage.tsx")), "SvgStage copied");
  assert.ok(await exists(path.join(target, ".faraday/packs/sim2d/SKILL.md")), "folder skill installed");
});

test("installPack(lecture-design) installs a skill FOLDER, no runtime", async () => {
  const target = await scaffold("Pedagogy Host");
  const result = await installPack("lecture-design", { fromDir: target });

  // skill reference is a directory -> the whole folder is installed
  for (const f of ["overview.md", "spaced-retrieval.md", "methods.md"]) {
    assert.ok(await exists(path.join(target, ".faraday/packs/lecture-design", f)), `${f} installed`);
  }
  assert.equal(result.addedDeps.length, 0, "skill-only pack adds no deps");
  const agents = await read(target, "AGENTS.md");
  assert.ok(agents.includes("Pack `lecture-design`:"), "AGENTS.md pointer added");
});

test("installPack(three) wires the runtime half AND the skill half", async () => {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "Pack Host", uuid: () => "fixed-id" });

  const result = await installPack("three", { fromDir: target });
  assert.equal(result.lessonRoot, target);

  // runtime half: deps pinned + sorted
  const pkg = JSON.parse(await read(target, "package.json"));
  assert.equal(pkg.dependencies["@faraday-academy/three"], "0.2.0");
  assert.ok(pkg.dependencies["@react-three/fiber"]);
  assert.ok(pkg.devDependencies["@types/three"]);
  const keys = Object.keys(pkg.dependencies);
  assert.deepEqual(keys, [...keys].sort((a, b) => a.localeCompare(b)), "deps stay sorted");

  // runtime half: css import injected
  const css = await read(target, "src/app.css");
  assert.ok(css.includes('@import "@faraday-academy/three/styles.css";'), "three css wired");

  // runtime half: examples copied
  assert.ok(await exists(path.join(target, "docs/examples/curriculum3d.tsx")), "example copied");

  // skill half: reference installed + pointer in AGENTS.md
  assert.ok(await exists(path.join(target, ".faraday/packs/three/pack.md")), "skill ref installed");
  const agents = await read(target, "AGENTS.md");
  assert.ok(agents.includes("Pack `three`:"), "AGENTS.md pointer added");

  // provenance records the pack
  const prov = JSON.parse(await read(target, ".faraday/provenance.json"));
  assert.ok(prov.packs.includes("three"), "provenance records the pack");
});

test("installPack is idempotent + supports the physics variant", async () => {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "Pack Host 2", uuid: () => "fixed-id" });

  await installPack("three", { fromDir: target, variant: "physics" });
  await installPack("three", { fromDir: target, variant: "physics" }); // twice = no dupes

  const pkg = JSON.parse(await read(target, "package.json"));
  assert.ok(pkg.dependencies["@react-three/rapier"], "physics variant dep pinned");

  const css = await read(target, "src/app.css");
  const occurrences = css.split('@import "@faraday-academy/three/styles.css";').length - 1;
  assert.equal(occurrences, 1, "css import not duplicated on re-run");

  const agents = await read(target, "AGENTS.md");
  const pointers = agents.split("Pack `three`:").length - 1;
  assert.equal(pointers, 1, "AGENTS.md pointer not duplicated on re-run");

  const prov = JSON.parse(await read(target, ".faraday/provenance.json"));
  assert.equal(prov.packs.filter((p) => p === "three:physics").length, 1, "provenance not duplicated");
});

test("installPack rejects an unknown pack, a lesson-less dir, and a bad variant", async () => {
  const base = await tmp();
  // unknown pack fails at manifest read, before the lesson lookup
  await assert.rejects(() => installPack("nope", { fromDir: base }), /Unknown pack: nope/);
  // a dir with no lesson above it
  await assert.rejects(() => installPack("three", { fromDir: base }), /not inside a Faraday lesson/);

  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "Pack Host 3", uuid: () => "fixed-id" });
  await assert.rejects(() => installPack("three", { fromDir: target, variant: "nonsense" }), /no variant/);
});

test("validateManifest catches shape errors and passes real packs", async () => {
  assert.deepEqual(validateManifest({ displayName: "ok" }), []);
  // a real shipped pack validates clean
  const three = await resolvePack("three");
  assert.deepEqual(validateManifest(await readManifestAt(three.packDir)), []);

  const errs = validateManifest({
    runtime: { copy: [{ from: "x" }], dependencies: { pkg: 1 } },
    skill: { reference: 5 },
  });
  assert.ok(errs.some((e) => /displayName is required/.test(e)));
  assert.ok(errs.some((e) => /runtime\.copy\[0\]/.test(e)));
  assert.ok(errs.some((e) => /runtime\.dependencies/.test(e)));
  assert.ok(errs.some((e) => /skill\.reference/.test(e)));
});

test("resolvePack(deck) aliases to slide-view", async () => {
  const r = await resolvePack("deck");
  assert.equal(r.name, "slide-view");
  assert.ok(await exists(path.join(r.packDir, "pack.json")));
});

test("resolvePack classifies official names and local paths", async () => {
  const off = await resolvePack("three");
  assert.equal(off.name, "three");
  assert.equal(off.source, "three");
  assert.ok(await exists(path.join(off.packDir, "pack.json")));
  await assert.rejects(() => resolvePack("does-not-exist"), /Unknown pack/);

  // a local pack dir
  const base = await tmp();
  const packDir = path.join(base, "my-pack");
  await fs.mkdir(packDir, { recursive: true });
  await fs.writeFile(
    path.join(packDir, "pack.json"),
    JSON.stringify({ displayName: "Mine", skill: { reference: "g.md" } }),
  );
  await fs.writeFile(path.join(packDir, "g.md"), "# guide");
  const local = await resolvePack(packDir);
  assert.equal(local.packDir, packDir);
  assert.equal(local.source, packDir);
});

// Opt-in packs: shipped but NOT default. Presentations are a pick-one choice you
// add (`faraday pack add <name>`), unlike the batteries-included capability packs.
const OPT_IN_PACKS = ["map2d", "stem-methods"];

test("default packs: every capability pack is default, presentations are opt-in", async () => {
  const defaults = await defaultPackNames();
  const all = (await listPacks()).map((p) => p.name);
  const expectedDefaults = all.filter((n) => !OPT_IN_PACKS.includes(n));
  assert.deepEqual([...defaults].sort(), [...expectedDefaults].sort(), "capability packs default; opt-in packs not");
  for (const n of OPT_IN_PACKS) assert.ok(!defaults.includes(n), `${n} is opt-in, not default`);

  // folder skill (lecture-design) → multiple files
  const ld = await resolvePack("lecture-design");
  const ldFiles = await readPackSkill(ld.packDir, await readManifestAt(ld.packDir));
  assert.ok(ldFiles.length > 1, "lecture-design skill is a multi-file folder");
  assert.ok(ldFiles.every((f) => f.path.endsWith(".md") && typeof f.content === "string"));

  // file skill (audience) → single file
  const aud = await resolvePack("audience");
  const audFiles = await readPackSkill(aud.packDir, await readManifestAt(aud.packDir));
  assert.equal(audFiles.length, 1, "audience skill is a single file");
  assert.match(audFiles[0].content, /Audience/);
});

test("installPack(textbook-view) copies TextbookView, no new deps", async () => {
  const target = await scaffold("Textbook Host");
  const before = JSON.parse(await read(target, "package.json"));
  await installPack("textbook-view", { fromDir: target });

  assert.ok(await exists(path.join(target, "src/lesson/textbook-view/TextbookView.tsx")));
  assert.ok(await exists(path.join(target, ".faraday/packs/textbook-view/pack.md")));
  const after = JSON.parse(await read(target, "package.json"));
  assert.deepEqual(after.dependencies, before.dependencies);
});

test("installPack(notes) copies the author-editable pen component, no new deps", async () => {
  const target = await scaffold("Notes Host");
  const before = JSON.parse(await read(target, "package.json"));
  await installPack("notes", { fromDir: target });

  assert.ok(await exists(path.join(target, "src/lesson/notes/Notebook.tsx")), "Notebook copied");
  assert.ok(await exists(path.join(target, ".faraday/packs/notes/pack.md")), "skill installed");
  const after = JSON.parse(await read(target, "package.json"));
  assert.deepEqual(after.dependencies, before.dependencies, "notes adds no runtime deps");
});

test("pack show routes a folder skill via its entry, a sub-file, and --all", async () => {
  // folder skill with entry -> prints just the index (overview.md), plus a 'more' hint
  const idx = await cli(["pack", "show", "lecture-design"]);
  assert.match(idx.out, /overview/i, "printed the entry file");
  assert.match(idx.out, /more in this pack:/, "listed the sub-files to fetch");
  assert.doesNotMatch(idx.out, /Space and retrieve/, "did NOT dump the sub-files by default");

  // a specific sub-file
  const one = await cli(["pack", "show", "lecture-design", "spaced-retrieval.md"]);
  assert.match(one.out, /Space and retrieve/, "printed the requested sub-file");
  assert.doesNotMatch(one.out, /more in this pack:/, "no index hint when a file is requested");

  // --all concatenates every file with headers
  const all = await cli(["pack", "show", "lecture-design", "--all"]);
  assert.match(all.out, /===== overview.md =====/);
  assert.match(all.out, /===== spaced-retrieval.md =====/);

  // exam pack front door
  const exam = await cli(["pack", "show", "exam"]);
  assert.match(exam.out, /practice test/i, "exam SKILL.md is the entry");

  // unknown sub-file errors
  await assert.rejects(() => cli(["pack", "show", "exam", "nope.md"]), /no file/);
});

test("exam pack: folder skill with an index + sub-guides, skill-only", async () => {
  const exam = await resolvePack("exam");
  const manifest = await readManifestAt(exam.packDir);
  assert.equal(manifest.skill.entry, "SKILL.md");
  assert.deepEqual(manifest.runtime ?? {}, {}, "exam adds no runtime deps");
  const files = await readPackSkill(exam.packDir, manifest);
  const paths = files.map((f) => f.path);
  assert.ok(paths.includes("SKILL.md"), "has the index");
  assert.ok(paths.includes("blueprint.md") && paths.includes("scoring-feedback.md"), "has sub-guides");
  assert.deepEqual(validateManifest(manifest), [], "exam manifest is valid");
});

test("faraday new auto-installs every default pack, --no-defaults opts out", async () => {
  const withBase = await tmp();
  await generateLesson({ targetDir: path.join(withBase, "l"), name: "Def On", uuid: () => "id" });
  const prov = JSON.parse(await read(path.join(withBase, "l"), ".faraday/provenance.json"));
  const defaults = await defaultPackNames();
  assert.deepEqual([...prov.packs].sort(), [...defaults].sort(), "every default pack recorded");
  // opt-in packs (e.g. the map2d presentation) are shipped but NOT auto-installed
  assert.ok(!prov.packs.includes("map2d"), "opt-in map2d not auto-installed");
  assert.ok(await exists(path.join(withBase, "l", ".faraday/packs/audience/audience.md")), "audience skill installed");
  assert.ok(await exists(path.join(withBase, "l", ".faraday/packs/lecture-design/overview.md")), "lecture-design folder installed");
  // heavy runtime packs are defaults too now: three pins its R3F deps
  const pkg = JSON.parse(await read(path.join(withBase, "l"), "package.json"));
  assert.ok(pkg.dependencies["@faraday-academy/three"], "three (a default) pinned its runtime deps");

  const noDef = await tmp();
  await generateLesson({ targetDir: path.join(noDef, "l"), name: "Def Off", noDefaults: true, uuid: () => "id" });
  const prov2 = JSON.parse(await read(path.join(noDef, "l"), ".faraday/provenance.json"));
  assert.ok(!(prov2.packs ?? []).length, "no default packs with --no-defaults");
});

test("removePack un-registers a pack and reverses its unshared deps/css", async () => {
  const target = await scaffold("Remove Host");
  await installPack("three", { fromDir: target });
  assert.ok(await exists(path.join(target, ".faraday/packs/three/pack.md")), "installed first");

  const r = await removePack("three", { fromDir: target });
  assert.equal(r.manifestResolved, true);

  // skill half + pointer + provenance gone
  assert.equal(await exists(path.join(target, ".faraday/packs/three")), false, "skill dir removed");
  assert.ok(!(await read(target, "AGENTS.md")).includes("Pack `three`:"), "AGENTS.md pointer stripped");
  const prov = JSON.parse(await read(target, ".faraday/provenance.json"));
  assert.ok(!prov.packs.some((p) => (typeof p === "string" ? p : p.name).startsWith("three")), "provenance entry gone");

  // reversible runtime config reversed
  const pkg = JSON.parse(await read(target, "package.json"));
  assert.ok(!("@faraday-academy/three" in pkg.dependencies), "three dep removed");
  assert.ok(!(await read(target, "src/app.css")).includes("@faraday-academy/three/styles.css"), "three css removed");
  assert.ok(r.removedDeps.includes("@faraday-academy/three"));

  // copied files are reported, not deleted
  assert.ok(r.leftFiles.includes("docs/examples"));

  await assert.rejects(() => removePack("three", { fromDir: target }), /not installed/);
});

test("removePack keeps a dependency still required by another installed pack", async () => {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "Shared Deps", uuid: () => "fixed-id" });

  // a local pack that also depends on @react-three/fiber (shared with `three`)
  const packDir = path.join(base, "viz-pack");
  await fs.mkdir(packDir, { recursive: true });
  await fs.writeFile(
    path.join(packDir, "pack.json"),
    JSON.stringify({ displayName: "Viz", runtime: { dependencies: { "@react-three/fiber": "^9.0.0" } } }),
  );

  await installPack("three", { fromDir: target });
  await installPack("viz-pack", { fromDir: target, packDir, source: packDir });

  const r = await removePack("three", { fromDir: target });
  const pkg = JSON.parse(await read(target, "package.json"));
  assert.ok("@react-three/fiber" in pkg.dependencies, "shared dep kept");
  assert.ok(!("@faraday-academy/three" in pkg.dependencies), "unshared three dep removed");
  assert.ok(!r.removedDeps.includes("@react-three/fiber"), "shared dep not reported as removed");
});

test("installPack from an external (local) source records {name, source} in provenance", async () => {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "External Host", uuid: () => "fixed-id" });

  const packDir = path.join(base, "vocab-pack");
  await fs.mkdir(packDir, { recursive: true });
  await fs.writeFile(
    path.join(packDir, "pack.json"),
    JSON.stringify({ displayName: "Vocab", skill: { reference: "guide.md", loadWhen: "teaching vocab" } }),
  );
  await fs.writeFile(path.join(packDir, "guide.md"), "# vocab guide");

  const result = await installPack("vocab-pack", { fromDir: target, packDir, source: packDir });
  assert.equal(result.source, packDir);
  assert.ok(await exists(path.join(target, ".faraday/packs/vocab-pack/guide.md")), "skill installed");

  const prov = JSON.parse(await read(target, ".faraday/provenance.json"));
  const entry = prov.packs.find((p) => typeof p === "object" && p.name === "vocab-pack");
  assert.ok(entry, "external pack recorded as an object");
  assert.equal(entry.source, packDir);
});

test("pack new scaffolds each archetype with a folder skill + valid manifest", async () => {
  for (const kind of ["skill", "copy", "runtime"]) {
    const base = await tmp();
    const r = await scaffoldPack("demo-pack", { cwd: base, kind });
    assert.equal(r.kind, kind);
    assert.equal(r.skill, "folder", "default skill is a folder");
    // folder skill: an index that routes to sub-guides
    for (const f of ["pack.json", "skill/SKILL.md", "skill/using.md", "skill/pedagogy.md", "quality.md", "examples/demo-pack.tsx"]) {
      assert.ok(await exists(path.join(r.packDir, f)), `missing ${f}`);
    }
    assert.equal(
      await exists(path.join(r.packDir, "runtime/demo-pack/index.tsx")),
      kind === "copy",
      "copy archetype ships an author-editable component; others don't",
    );
    const manifest = await readManifestAt(r.packDir);
    assert.deepEqual(validateManifest(manifest), [], `${kind} manifest invalid`);
    assert.equal(manifest.default, true, "scaffolded packs are default (batteries-included)");
    assert.equal(manifest.skill?.reference, "skill", "skill points at the folder");
    assert.equal(manifest.skill?.entry, "SKILL.md", "folder skill declares an entry index");
  }
});

test("pack new --flat produces a single-file skill", async () => {
  const base = await tmp();
  const r = await scaffoldPack("tiny", { cwd: base, flat: true });
  assert.equal(r.skill, "flat");
  assert.ok(await exists(path.join(r.packDir, "skill/pack.md")), "single-file skill");
  assert.equal(await exists(path.join(r.packDir, "skill/SKILL.md")), false, "no folder index");
  const manifest = await readManifestAt(r.packDir);
  assert.equal(manifest.skill?.reference, "skill/pack.md");
  assert.equal(manifest.skill?.entry, undefined, "flat skill has no entry");
  assert.deepEqual(validateManifest(manifest), []);
});

test("pack new rejects a bad name, an unknown kind, and a non-empty target", async () => {
  const base = await tmp();
  await assert.rejects(() => scaffoldPack("Bad Name", { cwd: base }), /kebab-case/);
  await assert.rejects(() => scaffoldPack("ok", { cwd: base, kind: "bogus" }), /unknown --kind/);
  await scaffoldPack("taken", { cwd: base });
  await assert.rejects(() => scaffoldPack("taken", { cwd: base }), /not empty/);
  await scaffoldPack("taken", { cwd: base, overwrite: true }); // --overwrite allows it
});

test("a scaffolded pack round-trips: pack new -> pack add into a lesson", async () => {
  const base = await tmp();
  const { packDir } = await scaffoldPack("round-trip", { cwd: base, kind: "copy" });
  const lesson = await scaffold("Round Trip Host");
  await installPack(null, { fromDir: lesson, packDir, source: packDir });
  assert.ok(await exists(path.join(lesson, ".faraday/packs/round-trip/SKILL.md")), "folder skill index installed");
  assert.ok(await exists(path.join(lesson, ".faraday/packs/round-trip/using.md")), "folder skill sub-guide installed");
  assert.ok(await exists(path.join(lesson, "src/lesson/round-trip/index.tsx")), "runtime component copied");
  const prov = JSON.parse(await read(lesson, ".faraday/provenance.json"));
  assert.ok(prov.packs.some((p) => (typeof p === "string" ? p : p.name) === "round-trip"), "recorded in provenance");
});

test("validatePackDir catches on-disk breakage that shape-validation misses", async () => {
  const base = await tmp();
  const { packDir } = await scaffoldPack("vp", { cwd: base });

  // fresh scaffold: structurally valid, but warns about the unfilled TODOs
  let r = await validatePackDir(packDir);
  assert.deepEqual(r.errors, [], "fresh scaffold has no errors");
  assert.ok(r.warnings.some((w) => /TODO/.test(w)), "unfilled scaffold is flagged");

  // dead skill.entry -> error (shape-validation would pass this)
  const manifestPath = path.join(packDir, "pack.json");
  const m = JSON.parse(await fs.readFile(manifestPath, "utf8"));
  assert.deepEqual(validateManifest({ ...m, skill: { ...m.skill, entry: "GONE.md" } }), [], "shape check alone accepts a dead entry");
  await fs.writeFile(manifestPath, JSON.stringify({ ...m, skill: { ...m.skill, entry: "GONE.md" } }, null, 2));
  r = await validatePackDir(packDir);
  assert.ok(r.errors.some((e) => /entry .*GONE\.md.* not found/.test(e)), "dead entry is an error");

  // missing quality file -> error
  await fs.writeFile(manifestPath, JSON.stringify(m, null, 2)); // restore
  await fs.rm(path.join(packDir, "quality.md"));
  r = await validatePackDir(packDir);
  assert.ok(r.errors.some((e) => /quality .*does not exist/.test(e)), "missing quality file is an error");
});

test("validatePackDir warns on a copy source that installs nothing", async () => {
  const base = await tmp();
  const { packDir } = await scaffoldPack("cp", { cwd: base, kind: "copy" });
  await fs.rm(path.join(packDir, "runtime"), { recursive: true, force: true });
  const r = await validatePackDir(packDir);
  assert.deepEqual(r.errors, [], "a missing copy source is not fatal (installer skips it)");
  assert.ok(r.warnings.some((w) => /runtime\/cp.*install nothing/.test(w)), "but it is warned");
});

test("every shipped official pack passes deep validation", async () => {
  for (const p of await listPacks()) {
    const { errors } = await validatePackDir((await resolvePack(p.name)).packDir);
    assert.deepEqual(errors, [], `${p.name} has on-disk errors: ${errors.join("; ")}`);
  }
});

// CLI-path tests: drive runFaradayCli end-to-end so a missing import / broken wiring
// in runPack* is caught (unit tests that call installPack/validatePackDir directly
// would not have caught the `validateManifest is not defined` regression in pack add).
test("CLI: faraday pack add installs an official pack into a lesson", async () => {
  const lesson = await scaffold("Cli Add Host");
  const r = await cli(["pack", "add", "srs", "--dir", lesson]);
  assert.equal(r.code, 0, `pack add failed: ${r.err}`);
  assert.ok(await exists(path.join(lesson, "src/lesson/srs/Flashcards.tsx")), "runtime half installed");
  assert.ok(await exists(path.join(lesson, ".faraday/packs/srs/pack.md")), "skill half installed");
});

test("CLI: faraday pack validate reports OK for an official pack, errors for a broken one", async () => {
  const ok = await cli(["pack", "validate", "exam"]);
  assert.equal(ok.code, 0);
  assert.match(ok.out, /OK/);

  const base = await tmp();
  const { packDir } = await scaffoldPack("brk", { cwd: base });
  await fs.rm(path.join(packDir, "quality.md")); // referenced but now missing
  // expected failure: drive runFaradayCli directly (throwOnError off) to capture exit code + stderr
  let code = 0, err = "";
  await runFaradayCli(["pack", "validate", packDir], {
    cwd: process.cwd(), stdout: () => {}, stderr: (s) => (err += s), setExitCode: (c) => (code = c),
  });
  assert.equal(code, 2, "a pack missing a referenced file must fail");
  assert.match(err, /quality .*does not exist/);
});

test("CLI: faraday pack new then add round-trips through the CLI", async () => {
  const base = await tmp();
  const newRes = await cli(["pack", "new", "cli-cap", "--kind", "copy", "--at", path.join(base, "cli-cap"), "--json"]);
  assert.equal(newRes.code, 0);
  const lesson = await scaffold("Cli New Host");
  const addRes = await cli(["pack", "add", path.join(base, "cli-cap"), "--dir", lesson]);
  assert.equal(addRes.code, 0, `pack add failed: ${addRes.err}`);
  assert.ok(await exists(path.join(lesson, ".faraday/packs/cli-cap/SKILL.md")), "folder skill installed via CLI");
});

test("installPack installs a pack's required packs first (composition)", async () => {
  const base = await tmp();
  const { packDir } = await scaffoldPack("needs-srs", { cwd: base });
  const m = JSON.parse(await read(packDir, "pack.json"));
  m.requires = ["srs"]; // depend on the official srs pack
  await fs.writeFile(path.join(packDir, "pack.json"), JSON.stringify(m, null, 2));

  // a minimal lesson WITHOUT default packs, so srs is genuinely not present yet
  const lessonBase = await tmp();
  const lesson = path.join(lessonBase, "l");
  await generateLesson({ targetDir: lesson, name: "Compose Host", noDefaults: true, uuid: () => "id" });
  assert.equal(await exists(path.join(lesson, "src/lesson/srs/Flashcards.tsx")), false, "srs not pre-installed");

  const r = await installPack(null, { fromDir: lesson, packDir, source: packDir });
  assert.deepEqual(r.installedRequires, ["srs"], "required pack installed first");
  assert.ok(await exists(path.join(lesson, "src/lesson/srs/Flashcards.tsx")), "dependency runtime pulled in");
  assert.ok(await exists(path.join(lesson, ".faraday/packs/srs/pack.md")), "dependency skill pulled in");
  const prov = JSON.parse(await read(lesson, ".faraday/provenance.json"));
  assert.ok(prov.packs.includes("srs"), "dependency recorded in provenance");
});

test("installPack requires are cycle-guarded (mutually-requiring packs terminate)", async () => {
  const base = await tmp();
  const a = await scaffoldPack("cyc-a", { cwd: base, dir: path.join(base, "cyc-a") });
  const b = await scaffoldPack("cyc-b", { cwd: base, dir: path.join(base, "cyc-b") });
  const setReq = async (dir, req) => {
    const p = path.join(dir, "pack.json");
    const mm = JSON.parse(await fs.readFile(p, "utf8"));
    mm.requires = [req];
    await fs.writeFile(p, JSON.stringify(mm, null, 2));
  };
  await setReq(a.packDir, b.packDir); // a → b
  await setReq(b.packDir, a.packDir); // b → a  (cycle)

  const lessonBase = await tmp();
  const lesson = path.join(lessonBase, "l");
  await generateLesson({ targetDir: lesson, name: "Cycle Host", noDefaults: true, uuid: () => "id" });

  // must terminate and install both exactly once
  const r = await installPack(null, { fromDir: lesson, packDir: a.packDir, source: a.packDir });
  assert.deepEqual(r.installedRequires, ["cyc-b"], "a installs b once");
  assert.ok(await exists(path.join(lesson, ".faraday/packs/cyc-a/SKILL.md")), "a installed");
  assert.ok(await exists(path.join(lesson, ".faraday/packs/cyc-b/SKILL.md")), "b installed");
});
